version: "3"
services:
  express-container:
    build:
      context: .
      target: production
    container_name: express-container
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    command: npm start  