version: "3"
services:
  express-container:
    container_name: express-container
    image: kareem966/aws-docker-lab1
    volumes:
      - ./src:/app/src:ro
    ports:
      - "4000:4000"
    depends_on: 
      # - postgres
      - redis 

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example    

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH: null  
  #   depends_on: 
  #     - mongo  

  redis:
    image: redis  

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - express-container

  # postgres:
  #   image: postgres
  #   restart: always
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD : example       

volumes:
  mongo-data:
  #postgres-data:
